name: first_aid_lite
description: An offline mobile application for first-aid awareness and emergency guidance.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/first-aid-icon.png"


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/first-aid.jpg
  android: true
  ios: true
  fullscreen: true


dependencies:
  flutter:
    sdk: flutter
  
  # Local storage for offline functionality
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.6
  
  # State management (if needed later)
  provider: ^6.0.5
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  # For generating Hive adapters (if needed later)
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  # Add your assets here
  assets:
    - assets/images/
    - assets/icons/
  
  # Add custom fonts if needed
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700